spring:
    application:
        name: data-contest
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create
        show-sql: true

    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB      # 단일 파일 최대 크기
            max-request-size: 500MB   # 전체 요청의 최대 크기
cloud:
    aws:
        credentials:
            accessKey: ${S3_ACCESS_KEY}
            secretKey: ${S3_SECRET_ACCESS_KEY}
        s3:
            bucket: ${S3_BUCKET_NAME}
        region:
            static: ${S3_REGION}
        stack:
            auto: false


public-api:
    key: ${API_SERVICE_KEY}
